const typography = require('@tailwindcss/typography')
const animate = require('tailwindcss-animate')
const defaultTheme = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ['class'],
    safelist: ['dark'],
    prefix: '',
    theme: {
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        fontSize: {
            display: ['4.25rem', { lineHeight: '6.25rem', letterSpacing: '-0.225rem' }],
            h1: ['4.5rem', { lineHeight: '5.625rem', letterSpacing: '-0.17rem' }],
            h2: ['3.75rem', { lineHeight: '4.5rem', letterSpacing: '-0.12rem' }],
            h3: ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.08rem' }],
            h4: ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.05rem' }],
            h5: ['1.875rem', { lineHeight: '2.25rem', letterSpacing: '-0.02rem' }],
            h6: ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.01rem' }],
            bodyL: ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '0rem' }],
            bodyM: ['1rem', { lineHeight: '1.5rem', letterSpacing: '0rem' }],
            bodyS: ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0rem' }],
            captionL: ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0rem' }],
            captionM: ['0.75rem', { lineHeight: '1rem', letterSpacing: '0rem' }],
            captionS: ['0.625rem', { lineHeight: '0.875rem', letterSpacing: '0rem' }],
        },
        boxShadow: {
            'none': '0 0 #0000',
            'xs': '0px 1px 2px 0px rgba(20, 21, 26, 0.05)',
            'sm': '0px 1px 3px 0px rgba(20, 21, 26, 0.10), 0px 1px 2px 0px rgba(20, 21, 26, 0.06)',
            'md': '0px 3px 6px -1px rgba(20, 21, 26, 0.08), 0px 2px 4px -1px rgba(20, 21, 26, 0.06)',
            'lg': '0px 10px 16px -3px rgba(20, 21, 26, 0.08), 0px 3px 6px -2px rgba(20, 21, 26, 0.05)',
            'xl': '0px 18px 24px -5px rgba(20, 21, 26, 0.10), 0px 8px 8px -5px rgba(20, 21, 26, 0.05)',
            '2xl': '0px 24px 48px -12px rgba(20, 21, 26, 0.24)',
        },
        extend: {
            colors: {
                'border': 'hsl(var(--border))',
                'input': 'hsl(var(--input))',
                'ring': 'hsl(var(--ring))',
                'background': 'hsl(var(--background))',
                'foreground': 'hsl(var(--foreground))',
                'primary': {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                'secondary': {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                'destructive': {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                'muted': {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                'accent': {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                'popover': {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                'card': {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                'light-blue': '#e3eafd',
                'dark-blue': '#133a9a',
                'border-alpha': 'rgba(10, 15, 41, 0.08)',
                'border-action-success-hover': '#8CE8B6',
                'border-action-focus': '#924FE8',
                'border-action-info-hover': '#93AFF6',
                'border-action-success': '#9AF4C3',
                'border-action-info': '#B4C7F8',
                'border-action-focus-light': '#B78AF0',
                'border-action-hover': '#C8CAD0',
                'border-action-normal': '#DEE0E3',
                'border-action-focus-destructive': '#E6483D',
                'border-action-destructive-disabled': 'rgba(230, 72, 61, 0.2)',
                'border-action-disabled': '#E9EAEC',
                'border-action-focus-destructive-light': '#F08B85',
                'border-action-destructive-hover': '#F5B2AD',
                'border-action-destructive': '#F7C3C0',
                'border-action-warning-hover': '#F9C594',
                'border-action-warning': '#FADA09',
                'border-base-alpha': 'rgba(10, 15, 41, 0.08)',
                'border-base-inverted': '#0B0C0E',
                'border-base-success': '#9AF4C3',
                'border-base-info': '#B4C7F8',
                'border-base-neutral-subtle': '#C8CAD0',
                'border-base-brand': '#D8C0F7',
                'border-base-neutral': '#DEE0E3',
                'border-base-divider': '#E9EAEC',
                'border-base-destructive': '#F7C3C0',
                'border-base-surface-neutral': '#F7F7F8',
                'border-base-warning': '#FADA09',
                'border-base-surface': '#FFFFFF',
                'border-base-alpha-white': 'rgba(255, 255, 255, 0.18)',
                'text-primary': '#14151A',
                'text-secondary': 'rgba(15, 19, 36, 0.6)',
                'text-tertiary': 'rgba(13, 17, 38, 0.4)',
                'text-quaternary': 'rgba(10, 15, 41, 0.25)',
                'text-blue': '#133A9A',
                'text-blue-inverted': '#133A9A',
                'text-green': '#166E3F',
                'text-green-inverted': '#166E3F',
                'text-green-accent': '#26BD6C',
                'text-green-secondary': 'rgba(#26BD6C, 0.5)',
                'text-green-tertiary': 'rgba(#26BD6C, 0.3)',
                'text-blue-secondary': 'rgba(#3368F0, 0.5)',
                'text-blue-tertiary': 'rgba(#3368F0, 0.3)',
                'text-blue-accent': '#4778F5',
                'text-purple-inverted': '#5314A3',
                'text-purple': '#5314A3',
                'text-purple-secondary': 'rgba(#873DE6, 0.5)',
                'text-purple-tertiary': 'rgba(#873DE6, 0.3)',
                'text-purple-accent': '#924FE8',
                'text-red-inverted': '#9A1C13',
                'text-red': '#9A1C13',
                'text-orange': '#AE590A',
                'text-orange-inverted': '#AE590A',
                'text-red-accent': '#E6483D',
                'text-red-secondary': 'rgba(#E6483D, 0.5)',
                'text-red-tertiary': 'rgba(#E6483D, 0.3)',
                'text-orange-accent': '#F48E2F',
                'text-orange-secondary': 'rgba(#F48E2F, 0.5)',
                'text-orange-tertiary': 'rgba(#F48E2F, 0.3)',
                'text-sub-600': '#525866',
                'icon-primary': '#4778F5',
                'icon-inverted': '#FFFFFF',
                'icon-dark-quaternary': 'rgba(10, 15, 41, 0.25)',
                'icon-dark-tertiary': 'rgba(13, 17, 38, 0.4)',
                'icon-dark-secondary': 'rgba(15, 19, 36, 0.6)',
                'icon-white-default': '#FFFFFF',
                'icon-white-secondary': 'rgba(255, 255, 255, 0.6)',
                'icon-white-tertiary': 'rgba(255, 255, 255, 0.46)',
                'icon-white-quaternary': 'rgba(255, 255, 255, 0.4)',
                'icon-static-dark-quaternary': 'rgba(10, 15, 41, 0.25)',
                'icon-static-dark-tertiary': 'rgba(13, 17, 38, 0.4)',
                'icon-static-dark-secondary': 'rgba(15, 19, 36, 0.6)',
                'icon-static-white-default': '#FFFFFF',
                'icon-static-white-secondary': 'rgba(255, 255, 255, 0.6)',
                'icon-static-white-tertiary': 'rgba(255, 255, 255, 0.46)',
                'icon-static-white-quaternary': 'rgba(255, 255, 255, 0.4)',
                'icon-base-quaternary': 'rgba(10, 15, 41, 0.25)',
                'icon-base-static-dark-quaternary': 'rgba(10, 15, 41, 0.25)',
                'icon-base-static-dark-tertiary': 'rgba(13, 17, 38, 0.4)',
                'icon-base-tertiary': 'rgba(13, 17, 38, 0.4)',
                'icon-base-static-dark-secondary': 'rgba(15, 19, 36, 0.6)',
                'icon-base-secondary': 'rgba(15, 19, 36, 0.6)',
                'icon-base-static-dark': '#14151A',
                'icon-base-static-white': '#FFFFFF',
                'icon-base-static-white-secondary': 'rgba(255, 255, 255, 0.6)',
                'icon-base-static-white-tertiary': 'rgba(255, 255, 255, 0.46)',
                'icon-base-static-white-quaternary': 'rgba(255, 255, 255, 0.4)',
                'icon-base-inverted-secondary': 'rgba(255, 255, 255, 0.6)',
                'icon-base-inverted-tertiary': 'rgba(255, 255, 255, 0.46)',
                'icon-base-inverted-quaternary': 'rgba(255, 255, 255, 0.4)',
                'background-surface-default': '#FFFFFF',
                'background-surface-inverted': '#0B0C0E',
                'background-surface-success-accent': '#26BD6C',
                'background-surface-info-accent': '#4778F5',
                'background-surface-success-subtle': '#D1FAE4',
                'background-surface-info-subtle': '#E3EAFD',
                'background-surface-destructive-accent': '#E6483D',
                'background-surface-neutral-subtle': '#E9EAEC',
                'background-surface-success': '#EDFDF4',
                'background-surface-info': '#F0F4FE',
                'background-surface-warning-accent': '#F48E2F',
                'background-surface-neutral': '#F7F7F8',
                'background-surface-destructive-subtle': '#FCE5E4',
                'background-surface-warning-subtle': '#FDEAD8',
                'background-surface-destructive': '#FDF2F1',
                'background-surface-warning': '#FEF4EC',
                'background-default': '#FFFFFF',
                'background-overlay-active-hover': 'rgba(10, 15, 41, 0.08)',
                'background-overlay-custom': 'rgba(10, 15, 41, 0.08)',
                'background-overlay-hover': 'rgba(10, 15, 41, 0.04)',
                'background-overlay-active-normal': 'rgba(10, 15, 41, 0.04)',
                'background-overlay-normal': 'rgba(255, 255, 255, 0.01)',
                'background-badge-green-accent': '#26BD6C',
                'background-badge-blue-accent': '#4778F5',
                'background-badge-gray-accent': '#5E636E',
                'background-badge-purple-accent': '#924FE8',
                'background-badge-green': '#D1FAE4',
                'background-badge-blue': '#E3EAFD',
                'background-badge-red-accent': '#E6483D',
                'background-badge-gray': '#E9EAEC',
                'background-badge-purple': '#ECDFFB',
                'background-badge-orange-accent': '#F48E2F',
                'background-badge-red': '#FCE5E4',
                'background-badge-orange': '#FDEAD8',
                'background-badge-surface': '#FFFFFF',
                'background-badge-white': '#FFFFFF',
                'background-accent-green-accent': '#26BD6C',
                'background-accent-blue-accent': '#4778F5',
                'background-accent-gray-accent': '#717684',
                'background-accent-purple-accent': '#924FE8',
                'background-accent-green-subtle': '#D1FAE4',
                'background-accent-blue-subtle': '#E3EAFD',
                'background-accent-red-accent': '#E6483D',
                'background-accent-gray-subtle': '#E9EAEC',
                'background-accent-purple-subtle': '#ECDFFB',
                'background-accent-green': '#EDFDF4',
                'background-accent-blue': '#F0F4FE',
                'background-accent-orange-accent': '#F48E2F',
                'background-accent-purple': '#F7F1FD',
                'background-accent-gray': '#F7F7F8',
                'background-accent-red-subtle': '#FCE5E4',
                'background-accent-orange-subtle': '#FDEAD8',
                'background-accent-red': '#FDF2F1',
                'background-accent-orange': '#FEF4EC',
                'background-button-tertiary-hover': 'rgba(10, 15, 41, 0.08)',
                'background-button-ghost-hover': 'rgba(10, 15, 41, 0.04)',
                'background-button-tertiary-disabled': 'rgba(10, 15, 41, 0.04)',
                'background-button-tertiary': 'rgba(10, 15, 41, 0.04)',
                'background-button-primary': '#4778F5',
                'background-button-primary-hover': '#133A9A',
                'background-button-destructive-hover': '#D9281C',
                'background-button-destructive': '#E6483D',
                'background-button-destructive-tertiary-hover': 'rgba(230, 72, 61, 0.15)',
                'background-button-destructive-tertiary-disabled': 'rgba(230, 72, 61, 0.1)',
                'background-button-destructive-tertiary': 'rgba(230, 72, 61, 0.1)',
                'background-button-primary-disabled': '#E9EAEC',
                'background-button-secondary-hover': '#F7F7F8',
                'background-button-destructive-disabled': '#FCE5E4',
                'background-button-destructive-secondary-hover': '#FDF2F1',
                'background-button-secondary': '#FFFFFF',
                'background-button-destructive-secondary-disabled': '#FFFFFF',
                'background-button-destructive-secondary': '#FFFFFF',
                'background-button-secondary-disabled': '#FFFFFF',
                'background-button-destructive-ghost-disabled': 'rgba(255, 255, 255, 0.01)',
                'background-button-ghost-disabled': 'rgba(255, 255, 255, 0.01)',
                'background-button-destructive-ghost': 'rgba(255, 255, 255, 0.01)',
                'background-button-ghost': 'rgba(255, 255, 255, 0.01)',
            },
            backgroundImage: {
                'hero': 'url(\'/hero-bg.svg\')',
                'features': 'url(\'/hero-bg.svg\')',
                'footer-left': 'url(\'/footer-left.svg\')',
                'footer-right': 'url(\'/footer-right.svg\')',
            },
            theme: {
                extend: {
                    fontFamily: {
                        sans: ['InterVariable', ...defaultTheme.fontFamily.sans],
                    },
                },
            },
            borderRadius: {
                xl: 'calc(var(--radius) + 4px)',
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: 0 },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: 0 },
                },
                'collapsible-down': {
                    from: { height: 0 },
                    to: { height: 'var(--radix-collapsible-content-height)' },
                },
                'collapsible-up': {
                    from: { height: 'var(--radix-collapsible-content-height)' },
                    to: { height: 0 },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
                'collapsible-down': 'collapsible-down 0.2s ease-in-out',
                'collapsible-up': 'collapsible-up 0.2s ease-in-out',
            },
        },
    },
    plugins: [animate, typography],
}
