alter table "public"."teams" drop constraint "teams_pkey";
drop index if exists "public"."teams_pkey";
create table "public"."team_members" (
    "id" bigint generated by default as identity not null,
    "invite_date" timestamp with time zone not null default now(),
    "team_id" uuid not null,
    "email" text not null,
    "role" text not null default 'member'::text
);
alter table "public"."team_members" enable row level security;
alter table "public"."invited_members" alter column "inviter" set not null;
alter table "public"."invited_members" alter column "team_id" set not null;
alter table "public"."teams" alter column "team_id" set not null;
CREATE UNIQUE INDEX team_members_pkey ON public.team_members USING btree (id);
CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id, team_id);
alter table "public"."team_members" add constraint "team_members_pkey" PRIMARY KEY using index "team_members_pkey";
alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";
alter table "public"."team_members" add constraint "team_members_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(team_id) not valid;
alter table "public"."team_members" validate constraint "team_members_team_id_fkey";
grant delete on table "public"."team_members" to "anon";
grant insert on table "public"."team_members" to "anon";
grant references on table "public"."team_members" to "anon";
grant select on table "public"."team_members" to "anon";
grant trigger on table "public"."team_members" to "anon";
grant truncate on table "public"."team_members" to "anon";
grant update on table "public"."team_members" to "anon";
grant delete on table "public"."team_members" to "authenticated";
grant insert on table "public"."team_members" to "authenticated";
grant references on table "public"."team_members" to "authenticated";
grant select on table "public"."team_members" to "authenticated";
grant trigger on table "public"."team_members" to "authenticated";
grant truncate on table "public"."team_members" to "authenticated";
grant update on table "public"."team_members" to "authenticated";
grant delete on table "public"."team_members" to "service_role";
grant insert on table "public"."team_members" to "service_role";
grant references on table "public"."team_members" to "service_role";
grant select on table "public"."team_members" to "service_role";
grant trigger on table "public"."team_members" to "service_role";
grant truncate on table "public"."team_members" to "service_role";
grant update on table "public"."team_members" to "service_role";
