create table "public"."invited_members" (
    "id" bigint generated by default as identity not null,
    "invite_date" timestamp with time zone not null default now(),
    "inviter" uuid,
    "email" text
);
alter table "public"."invited_members" enable row level security;
CREATE UNIQUE INDEX invited_member_pkey ON public.invited_members USING btree (id);
alter table "public"."invited_members" add constraint "invited_member_pkey" PRIMARY KEY using index "invited_member_pkey";
alter table "public"."invited_members" add constraint "invited_member_inviter_fkey" FOREIGN KEY (inviter) REFERENCES auth.users(id) not valid;
alter table "public"."invited_members" validate constraint "invited_member_inviter_fkey";
grant delete on table "public"."invited_members" to "anon";
grant insert on table "public"."invited_members" to "anon";
grant references on table "public"."invited_members" to "anon";
grant select on table "public"."invited_members" to "anon";
grant trigger on table "public"."invited_members" to "anon";
grant truncate on table "public"."invited_members" to "anon";
grant update on table "public"."invited_members" to "anon";
grant delete on table "public"."invited_members" to "authenticated";
grant insert on table "public"."invited_members" to "authenticated";
grant references on table "public"."invited_members" to "authenticated";
grant select on table "public"."invited_members" to "authenticated";
grant trigger on table "public"."invited_members" to "authenticated";
grant truncate on table "public"."invited_members" to "authenticated";
grant update on table "public"."invited_members" to "authenticated";
grant delete on table "public"."invited_members" to "service_role";
grant insert on table "public"."invited_members" to "service_role";
grant references on table "public"."invited_members" to "service_role";
grant select on table "public"."invited_members" to "service_role";
grant trigger on table "public"."invited_members" to "service_role";
grant truncate on table "public"."invited_members" to "service_role";
grant update on table "public"."invited_members" to "service_role";
